# Generated by Django 3.1.1 on 2020-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Agrede su nombre', max_length=50)),
                ('apellido', models.CharField(help_text='Agrede su Apellido', max_length=50)),
                ('Fecha', models.DateTimeField(help_text='Indique la decha y la hora')),
                ('numero_comensales', models.IntegerField(help_text='Indique en munero de personas')),
            ],
        ),
    ]
