# Generated by Django 3.1.1 on 2020-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_leña', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_comensales',
            field=models.IntegerField(max_length=50),
        ),
    ]
